# -*- coding: utf-8 -*-
"""day_03_maxscore.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11CUfs9QbtIVZYEvn0A-rziNJ6hNYz8MW
"""

score = {
    "Deepak" : "77",
    "Ajay" : "86",
    "Niruj" : "97",
    "Ashish" : "82",
    "Saquib" : "70"
}
max_score = max(score,key=score.get)
print(max_score + " got maximum score.")