# -*- coding: utf-8 -*-
"""Day_01_addition.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bKh8mUsZWriMfOQmZXxSGQxLCzvM1XG1
"""

x = input('Enter the values: ')
y = x.split()
print(y)

val = []

for i in y:
  val.append(int(i))

print(val)

SUM = sum(val)
print(SUM)